# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-10 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('clientIP', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('clientName', models.CharField(max_length=100)),
                ('clientStatus', models.BooleanField(default=False)),
                ('flag', models.BooleanField(default=False)),
                ('usbDetected', models.BooleanField(default=False)),
                ('internetDetected', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['flag'],
            },
        ),
    ]
